services:
  qdrant:
    image: qdrant/qdrant:v1.15.1 #latest!
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage  # persistenza dati

  ollama:
    image: ollama/ollama:0.11.11
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ./ollama_data:/root/.ollama   # cache e modelli scaricati
    ports:
      - "11434:11434"  # API REST Ollama
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g

  agents:
    build: ./agents   # cartella agents accanto al docker-compose.yml
    container_name: agents
    volumes:
      - ./agents:/app   # monta la cartella agents dentro /app
    working_dir: /app
    command: tail -f /dev/null  # mantiene il container attivo per sviluppo
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - ollama
      - qdrant

  indexing:
    build: ./indexing
    container_name: indexing
    volumes:
      - ./indexing:/app
      - ./data:/app/data
      - ./qdrant_storage:/qdrant/storage
    working_dir: /app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_URL=http://qdrant:6333
      - EMBED_MODEL=nomic-embed-text
      - COLLECTION=ing_info_mag_docs
    depends_on:
      - ollama
      - qdrant
    command: tail -f /dev/null  # mantiene il container attivo per sviluppo
